spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/lotto-web?authSource=admin
  main:
    allow-bean-definition-overriding: true
  task:
    scheduling:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

lotto:
  time:
    timeZone: "Europe/Warsaw"
  number-generator:
    facade:
      lowerBand: 1
      upperBand: 99
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
        connectionTimeout: 2000
        readTimeout: 2000
    lotteryRunOccurrence: "0 0 20 * * */6"
#    lotteryRunOccurrence: "*/15 * * * * *"



