spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/lotto-web?authSource=admin

lotto:
  number-generator:
    facade:
      lowerBand: 1
      upperBand: 99
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
        connectionTimeout: 2000
        readTimeout: 2000



